import { NextRequest, NextResponse } from "next/server";
import JSZip from "jszip";
import { prisma } from "@/lib/db/prisma";

export const runtime = "nodejs";

// ─── GET /api/export?projectId=xxx — zip download all generated files ─────────

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const projectId = searchParams.get("projectId");

  if (!projectId) {
    return NextResponse.json({ error: "projectId is required" }, { status: 400 });
  }

  // Fetch project + all files from DB
  let project;
  try {
    project = await prisma.project.findUnique({
      where: { id: projectId },
      include: {
        files: {
          orderBy: { createdAt: "asc" },
        },
      },
    });
  } catch (err) {
    console.error("DB error fetching project:", err);
    return NextResponse.json({ error: "Database error" }, { status: 500 });
  }

  if (!project) {
    return NextResponse.json({ error: "Project not found" }, { status: 404 });
  }

  if (project.files.length === 0) {
    return NextResponse.json({ error: "No files found for this project" }, { status: 404 });
  }

  // Build zip
  const zip = new JSZip();
  const folderName = `arrobuild-${projectId.slice(0, 8)}`;
  const folder = zip.folder(folderName);

  if (!folder) {
    return NextResponse.json({ error: "Failed to create zip folder" }, { status: 500 });
  }

  for (const file of project.files) {
    folder.file(file.fileName, file.content);
  }

  // Add a README that explains the files
  const readmeContent = `# ArroBuild — Generated Documentation

Project ID: ${project.id}
Generated: ${project.createdAt.toISOString()}

## Files Included

${project.files.map((f) => `- **${f.fileName}** — ${f.label}`).join("\n")}

## How to Use

1. Open each file in your preferred editor
2. Share with your AI coding assistant (Cursor, Claude Code, etc.)
3. Start building with a solid foundation!

Generated by [ArroBuild](https://arrobuild.com)
`;
  folder.file("README.md", readmeContent);

  // Fase 4.1: Custom Export Formats
  const getFileContent = (name: string) =>
    project.files.find((f) => f.fileName === name)?.content || "";

  const contextMd = getFileContent("context.md");
  const agentsMd = getFileContent("agents.md");
  const designSystemMd = getFileContent("design-system.md");
  const planMd = getFileContent("plan.md");

  // 1. CLAUDE.md
  if (contextMd || agentsMd) {
    const claudeContent = `
# Claude Code Instructions

You are acting as an AI Coding Agent using the context and agents defined below.
Please read these instructions carefully before starting any implementation.

## Context
${contextMd}

## Agents Role
${agentsMd}
`.trim();
    folder.file("CLAUDE.md", claudeContent);
  }

  // 2. .cursorrules
  if (designSystemMd || planMd) {
    const cursorRulesContent = `
# Cursor AI Rules

You are an expert developer assistant. Follow the design system and plan meticulously.

## Design System
${designSystemMd}

## Plan
${planMd}

## Coding Conventions
- Use TypeScript for all files
- Use TailwindCSS for styling
- Follow the exact design tokens specified in the Design System
- Prioritize clean, readable code with descriptive variable names
`.trim();
    folder.file(".cursorrules", cursorRulesContent);
  }

  // 3. agents.json
  if (agentsMd) {
    // Simple parsing logic: convert sections into JSON objects
    const agentsList = agentsMd
      .split("##")
      .slice(1)
      .map((section) => {
        const lines = section.trim().split("\\n");
        const name = lines[0].trim();
        const roleAndTasks = lines.slice(1).join("\\n").trim();
        return { name, instructions: roleAndTasks };
      });
    folder.file("agents.json", JSON.stringify({ agents: agentsList }, null, 2));
  }

  // 4. system-prompt.txt
  const megaPrompt = project.files
    .map((f) => `--- START OF ${f.fileName} ---\\n${f.content}\\n--- END OF ${f.fileName} ---`)
    .join("\\n\\n");
  
  const systemPromptContent = `
You are a master software engineer and AI agent. Below is the entire context, plan, and requirements for the project.
Read everything carefully and prepare to execute the plan.

${megaPrompt}
  `.trim();
  folder.file("system-prompt.txt", systemPromptContent);

  // Generate zip — use ArrayBuffer to satisfy strict BodyInit typing
  const zipUint8 = await zip.generateAsync({
    type: "uint8array",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });
  const zipBuffer = zipUint8.buffer.slice(
    zipUint8.byteOffset,
    zipUint8.byteOffset + zipUint8.byteLength
  ) as ArrayBuffer;

  return new Response(zipBuffer, {
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${folderName}.zip"`,
      "Content-Length": String(zipUint8.length),
      "Cache-Control": "no-store",
    },
  });
}
