import { NextRequest, NextResponse } from "next/server";
import JSZip from "jszip";
import { prisma } from "@/lib/db/prisma";
import { getSupabaseUser } from "@/lib/auth";

export const runtime = "nodejs";

export async function GET(req: NextRequest) {
  const supabaseUser = await getSupabaseUser();
  if (!supabaseUser) {
    return NextResponse.json({ error: "Login diperlukan" }, { status: 401 });
  }

  const { searchParams } = new URL(req.url);
  const projectId = searchParams.get("projectId");

  if (!projectId) {
    return NextResponse.json({ error: "projectId is required" }, { status: 400 });
  }

  let project;
  try {
    project = await prisma.project.findUnique({
      where: { id: projectId },
      include: {
        files: { orderBy: { createdAt: "asc" } },
      },
    });
  } catch (err) {
    console.error("DB error fetching project:", err);
    return NextResponse.json({ error: "Database error" }, { status: 500 });
  }

  if (!project) {
    return NextResponse.json({ error: "Project not found" }, { status: 404 });
  }

  if (project.userId !== supabaseUser.id) {
    return NextResponse.json(
      { error: "Anda tidak punya akses ke proyek ini" },
      { status: 403 }
    );
  }

  if (project.files.length === 0) {
    return NextResponse.json({ error: "No files found for this project" }, { status: 404 });
  }

  const zip = new JSZip();
  const folderName = `arrobuild-${projectId.slice(0, 8)}`;
  const folder = zip.folder(folderName);

  if (!folder) {
    return NextResponse.json({ error: "Failed to create zip folder" }, { status: 500 });
  }

  for (const file of project.files) {
    folder.file(file.fileName, file.content);
  }

  const readmeContent = `# ArroBuild — Generated Documentation

Project ID: ${project.id}
Generated: ${project.createdAt.toISOString()}

## Files Included

${project.files.map((f) => `- **${f.fileName}** — ${f.label}`).join("\n")}

Generated by [ArroBuild](https://arrobuild.com)
`;
  folder.file("README.md", readmeContent);

  const getFileContent = (name: string) =>
    project.files.find((f) => f.fileName === name)?.content || "";

  const contextMd = getFileContent("context.md");
  const agentsMd = getFileContent("agents.md");
  const designSystemMd = getFileContent("design-system.md");
  const planMd = getFileContent("plan.md");

  if (contextMd || agentsMd) {
    folder.file(
      "CLAUDE.md",
      `# Claude Code Instructions\n\n## Context\n${contextMd}\n\n## Agents Role\n${agentsMd}`.trim()
    );
  }

  if (designSystemMd || planMd) {
    folder.file(
      ".cursorrules",
      `# Cursor AI Rules\n\n## Design System\n${designSystemMd}\n\n## Plan\n${planMd}`.trim()
    );
  }

  const zipUint8 = await zip.generateAsync({
    type: "uint8array",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });
  const zipBuffer = zipUint8.buffer.slice(
    zipUint8.byteOffset,
    zipUint8.byteOffset + zipUint8.byteLength
  ) as ArrayBuffer;

  return new Response(zipBuffer, {
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${folderName}.zip"`,
      "Content-Length": String(zipUint8.length),
      "Cache-Control": "no-store",
    },
  });
}
